uauth/urls.py
from django.urls import path, re_path, include
from uauth.views import home, uregister, ulogin, upassword, ulogout

app_name = 'uauth'

urlpatterns = [
	re_path (r"^accounts/" , include("django.contrib.auth.urls")),

	re_path (r'^$',     home, name="home_index"),    
    re_path (r"^home/", home, name="home"),

    re_path (r'^logout/$'  , ulogout,   name='logout'),
	re_path (r'^register/$', uregister, name='register'),
 	re_path (r'^login/$'   , ulogin,    name='login'),
    re_path (r'^password/$', upassword, name='password'),

]

uct/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
#from django.conf.urls import handler400, handler403, handler404, handler500

#from uauth.views import logout, home, error_404, error_500

#handler400 = 'uct.views.error_400'
#handler403 = 'uct.views.error_403'
# handler404 = 'uauth.views.error_404'
# handler500 = 'uauth.views.error_500'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("uauth.urls")),
    path('', include('todo.urls')),
]

uauth/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('username','password','email')

uauth/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash, authenticate, login, logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from .forms import UserForm
from todo.forms import ResourceForm
from todo.models import Resource

# Create your views here.
def home(request):
	if request.user.is_authenticated:
		# do something if the user is authenticated
		return HttpResponseRedirect(reverse('todo_index'))
	else:
		return render(request, "uauth/login.html")

#		return render(request, "todo/todo_index.html")

# def index(request):
# 	return HttpResponseRedirect(reverse('todo_index'))

# @login_required
# def special(request):
# 	return HttpResponse("You are logged in !")

@login_required
def ulogout(request):
	logout(request)
	messages.success(request, 'You are logged out!')	
	return HttpResponseRedirect(reverse('uauth:home'))

def uregister(request):
	registered = False
	if request.method == 'POST':
		user_form = UserForm(data=request.POST)
		profile_form = ResourceForm(data=request.POST)
		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = profile_form.save(commit=False)
			profile.user = user
			if 'profile_pic' in request.FILES:
				print('found it')
				profile.profile_pic = request.FILES['profile_pic']
			profile.save()
			registered = True
		else:
			print(user_form.errors,profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = ResourceForm()
	
	return render(request,'uauth/registration.html',
					{
						'user_form':user_form,
						'profile_form':profile_form,
						'registered':registered
					}
				)

def ulogin(request):
	print ("Coming here....")
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		print("Authenticating user: {} and password: {}".format(username,password))		
		user = authenticate(username=username, password=password)
		if user:
			if user.is_active:
				login(request,user)
				res = Resource.objects.get (user__username = username)
				request.session ['can_edit_master_data'] = res.can_edit_master_data
				print ('Can edit flag: ', res.can_edit_master_data)
				return HttpResponseRedirect(reverse('todo_index'))
			else:
				return HttpResponse("Your account was inactive.")
		else:
			print("Someone tried to login and failed.")
			print("They used username: [{}] and password: [{}]".format(username,password))
			messages.error(request, 'Invalid login details given!')
			return render(request, 'uauth/login.html', {'errmsg':'Invalid login details given'})
	else:
		return render(request, 'uauth/login.html', {})

@login_required
def upassword(request):
	if request.method == 'POST':
		form = PasswordChangeForm (request.user, request.POST)
		if form.is_valid():
			user = form.save()
			update_session_auth_hash(request, user)  # Important!
			messages.success(request, 'Your password updated successfully! Sign-in again with new credentials.')
			logout(request)
			return HttpResponseRedirect(reverse('uauth:home'))		
		else:
			messages.error(request, 'Please correct the error below.')
	else:
		form = PasswordChangeForm(request.user)

	return render(request, 'uauth/password.html', {'form': form})

# def error_404 (request, exception):
# 	return render(request, 'uauth/404.html')

# def error_500 (request):
# 	return render(request, 'uauth/500.html')

uauth/templates/uauth/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>UCTodo</title>
    <link rel="shortcut icon" href="/static/uct/img/todoapp.ico">

    <script type="text/javascript" src="/static/jquery-3.3.1/js/jquery.min.js"></script>    
    <script type="text/javascript" src="/static/popper.js-1.14.3/js/popper.min.js"></script>

    <link rel="stylesheet" href="/static/bootstrap-4.5.3-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/open-iconic/font/css/open-iconic-bootstrap.css">
<!--    <link rel="stylesheet" href="/static/font-awesome/4.7.0/css/font-awesome.min.css"> -->
    <link rel="stylesheet" href="/static/bootstrap-select-1.13.14/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="/static/jquery-datetimepicker-2.5.20/css/jquery.datetimepicker.min.css"/>

    <script type="text/javascript" src="/static/jquery-datetimepicker-2.5.20/js/jquery.datetimepicker.min.js"></script> 
    <script type="text/javascript" src="/static/jquery-datetimepicker-2.5.20/js/jquery.datetimepicker.full.min.js"></script>        

    <script type="text/javascript" src="/static/bootstrap-4.5.3-dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap-select-1.13.14/js/bootstrap-select.min.js"></script>

    <link rel="stylesheet" href=/static/uct/css/base.css>
    <script type="text/javascript" src="{% static 'uct/js/core.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">

      <a class="navbar-brand" href="{% url 'uauth:home' %}">
        <img src="{% static 'uct/img/todoapp.png' %}" width="50" height="50" class="d-inline-block align-middle" alt="ToDoApp" loading="lazy"/>
        <span class="font-weight-bold">&nbsp;TODO://</span>
      </a>

      {% if request.session.can_edit_master_data %}
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="nav-link text-primary" href="{% url 'uauth:home' %}">TODO List</a></li>
          <li class="nav-item"><a class="nav-link text-primary" href="{% url 'todo_heatmap' %}">Heatmap</a></li>
          <li class="nav-item dropdown">
            <a aria-expanded="false" aria-haspopup="true" 
              class="font-weight-bold nav-link text-primary dropdown-toggle" 
              data-toggle="dropdown" href="#" role="button">
              Admin
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="/admin/todo/context">Manage Contexts</a>
              <a class="dropdown-item" href="/admin/todo/todotype">Manage TodoTypes</a>
              <a class="dropdown-item" href="/admin/todo/todostatus">Manage TodoStatus</a>              
            </div>
          </li>
        </ul>
      {% endif %}
  
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">

          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

          <ul class="navbar-nav mr-sm-3">&nbsp;&nbsp;
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a aria-expanded="false" aria-haspopup="true" 
                class="font-weight-bold nav-link dropdown-toggle" 
                data-toggle="dropdown" href="#" role="button">
                {{request.user.username}}
              </a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'uauth:logout' %}">Logout</a>
                <a class="dropdown-item" href="{% url 'uauth:password' %}">Password</a>
              </div>
            </li>
          {% else %}
            <a class="dropdown-item" href="{% url 'uauth:register' %}">Register</a>
          {% endif %}
          </ul>
        </form>
      </div>
    </nav>
  <div class="container">
    {% include 'uauth/messages.html' %}
  </div>

    {% block content %}
    {% endblock %}
  </body>
</html>

uauth/templates/uauth/login.html
{% extends './base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{{ form.media }}
<br>

<div  class="container">
	<div  class="row justify-content-center">
		<div  class="col-5"><br>
		<h1  class="text-center">Sign in</h1><br>
			<div  class="card">
				<div  class="card-body">
					<h4  class="card-title">Sign in to your account</h4>
					<hr>
					<form method="post" action="{% url 'uauth:login' %}">
						{% csrf_token %}
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-prepend">
									<span class="input-group-text"><span class="oi oi-person"></span></span>
								</div>
								<input name="username" class="form-control" autofocus required placeholder="Email or login" type="text"> <!-- type="email"> -->
							</div> <!-- input-group.// -->
						</div> <!-- form-group// -->
						<div class="form-group">
							<div class="input-group">
								<div class="input-group-prepend">
										<span class="input-group-text"> <span class="oi oi-lock-locked"></span></span>
								</div>
								<input name="password" class="form-control" required placeholder="******" type="password">
							</div> <!-- input-group.// -->
						</div> <!-- form-group// -->
						<div class="form-group">
							<div class="row px-3 mb-4">
								<div class="custom-control custom-checkbox custom-control-inline">
									<input id="chk2" type="checkbox" name="chk" class="custom-control-input">
									<label for="chk2" class="custom-control-label text-sm">Remember me</label>
								</div>
								<a href="#" class="ml-auto mb-0 text-sm">Forgot Password?</a>
							</div> <!-- row px-3 mb-4// -->  
						</div> <!-- form-group// -->  
						<button type="submit" class="btn btn-primary btn-block"> Login  </button>
					</form>
				</div>
			</div>
		</div>
    </div>
  </div>
{% endblock %}

uauth/templates/uauth/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

uauth/templates/uauth/password.html
<!--users/templates/registration/login.html-->
{% extends './base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{{ form.media }}
<div  class="container">
	<div  class="row justify-content-center">
		<div  class="col-5"><br>
<!--		<h1  class="text-center">Change Password</h1> -->
			<div  class="card">
				<div  class="card-body">
					<h4  class="card-title">Change your password</h4>
					<form  method="post">
						{% csrf_token %}
						{{ form|crispy }}
						<button  type="submit"  class="btn btn-success btn-block">Change password </button>
					</form>
				</div>
			</div>
		</div>
    </div>
  </div>
{% endblock %}

uauth/templates/uauth/registration.html
<!--users/templates/registration/login.html-->
{% extends './base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{{ form.media }}
<br>
<div class="container">
	<div class="jumbotron">
		{% if registered or request.user.is_authenticated %}
			<h1 class="display-6">Thank you for registering!</h1>
		{% else %}
			<h1 class="display-6">Regsiter here...</h1>
			<hr class="my-4">
			<form enctype="multipart/form-data" method="POST">
				{% csrf_token %}
          		{{ user_form.as_p }}
          		{{ profile_form.as_p }}
          		<input type="submit" name="" value="Register">
        	</form>
		{% endif %}
	</div>
</div>
{% endblock %}