todo/urls.py
from django.views.static import serve
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.contrib.auth.decorators import login_required

urlpatterns = [
	path('todo/',                 login_required(views.TodoIndexView.as_view()),  name='todo_index'),
	path('todo_detail/<int:pk>/', login_required(views.TodoDetailView.as_view()), name='todo_detail'),
	path('todo_create/',          views.todo_create,              name='todo_create'),	
	path('todo_edit/<int:pk>/',   views.todo_edit,                name='todo_edit'),
	path('todo_copyas/<int:pk>/', views.todo_copyas,              name='todo_copyas'),	
	path('todo_delete/<int:pk>/', views.todo_delete,              name='todo_delete'),
	path('todo_close/<int:pk>/',  views.todo_close,               name='todo_close'),

	re_path (r'^todo_heatmap/$',                      views.todo_heatmap,  name='todo_heatmap'),
	re_path (r'^todo_heatmap/(?P<start_date>\w+)/$',  views.todo_heatmap,  name='todo_heatmap'),

	re_path(
		r'^static/(?P<path>.*)$',
		serve,
		{'document_root': settings.STATIC_ROOT}), 
	re_path(
		r'^context-autocomplete/$',
		views.ContextAutocomplete.as_view (),
		name='context-autocomplete',
	),
]

uct/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
#from django.conf.urls import handler400, handler403, handler404, handler500

#from uauth.views import logout, home, error_404, error_500

#handler400 = 'uct.views.error_400'
#handler403 = 'uct.views.error_403'
# handler404 = 'uauth.views.error_404'
# handler500 = 'uauth.views.error_500'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("uauth.urls")),
    path('', include('todo.urls')),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import Group, User

class ResourceGroup (models.Model):
	user           = models.ForeignKey(User,on_delete=models.CASCADE)
	group          = models.ForeignKey(Group,on_delete=models.CASCADE)
	can_see_group_list   = models.BooleanField (default=False)
	can_edit_group_list  = models.BooleanField (default=False)

	class Meta:
		unique_together = ('user', 'group',)

	def __str__(self):
		return "User: "                 + self.user.username            + "\n" + \
		       "Group: "                + self.group.name               + "\n" + \
		       "can_edit_master_data: " + str(self.can_edit_master_data)  + "\n" + \
			   "can_see_group_list: "   + str(self.can_see_group_list)  + "\n" + \
			   "can_edit_group_list: "  + str(self.can_edit_group_list) + "\n"

class Resource (models.Model):
	user           = models.OneToOneField(User,on_delete=models.CASCADE)
	res_name       = models.CharField (max_length=120,null=True, blank=False)
	added_date     = models.DateTimeField (auto_now_add=True)
	portfolio_site = models.URLField(blank=True)
	profile_pic    = models.ImageField(upload_to='profile_pics',blank=True)
	can_edit_master_data = models.BooleanField (default=False)
	
	def __str__(self):
		return self.res_name + ' (' + self.user.username + ')'

class TodoStatus (models.Model):
	code   = models.CharField (max_length=60, blank=False, primary_key=True)
	name = models.CharField (max_length=120,null=True, blank=False)

	added_user   = models.ForeignKey ('Resource', on_delete=models.DO_NOTHING)
	added_date   = models.DateTimeField (auto_now_add=True)

	def __str__(self):
		return self.name

class TodoType (models.Model):
	code   = models.CharField (max_length=60, blank=False, primary_key=True)
	name = models.CharField (max_length=120,null=True, blank=False)

	added_user   = models.ForeignKey ('Resource', on_delete=models.DO_NOTHING)
	added_date   = models.DateTimeField (auto_now_add=True)

	def __str__(self):
		return self.name

class Context (models.Model):
	context_id   = models.CharField (max_length=60, blank=False, primary_key=True)
	context_name = models.CharField (max_length=120,null=True, blank=False)
	added_date   = models.DateTimeField (auto_now_add=True)

	def __str__(self):
		return self.context_id + ' (' + self.context_name + ')'

# Create your models here.
class Todo (models.Model):
	EFFORT_TYPES = (
		('H', 'Hour(s)'),
		('D', 'Day(s)'),
		('M', 'Month(s)'),
	)

	assigned_to  = models.ForeignKey ('Resource', on_delete=models.DO_NOTHING,  null=True, blank=True, related_name='assigned_to')
	context_id   = models.ForeignKey ('Context',  on_delete=models.DO_NOTHING,  null=True, blank=True)
	todo_type    = models.ForeignKey ('TodoType',  on_delete=models.DO_NOTHING, null=True, blank=True)
	short_desc   = models.CharField (max_length=200, help_text='Short description of the todo item ...', blank=True)
	effort_type  = models.CharField (max_length=1, choices=EFFORT_TYPES, null=True, blank=True)
	effort       = models.DecimalField (max_digits=5, decimal_places=0, null=True, blank=True)
	start_date   = models.DateTimeField (null=True, blank=True)
	end_date     = models.DateTimeField (null=True, blank=True)	
	status       = models.ForeignKey ('TodoStatus',  on_delete=models.DO_NOTHING, related_name='status', null=True, blank=True)
	group        = models.ForeignKey (Group,on_delete=models.DO_NOTHING, null=True, blank=True)

	added_user   = models.ForeignKey ('Resource', on_delete=models.DO_NOTHING, related_name='added_user', null=True, blank=True)
	added_date   = models.DateTimeField (auto_now_add=True)

	modified_user = models.ForeignKey ('Resource', on_delete=models.DO_NOTHING, related_name='modified_user', null=True, blank=True)
	modified_date = models.DateTimeField (auto_now=True)

	def __str__(self):
		return self.short_desc

class TodoNotes (models.Model):
	todo       = models.ForeignKey ('Todo', on_delete=models.CASCADE, null=False, blank=False)
	notes      = models.CharField (max_length=300, help_text='User log inforation ...', blank=False)
	added_user = models.ForeignKey ('Resource', on_delete=models.DO_NOTHING, null=False, blank=True)
	added_date = models.DateTimeField (auto_now_add=True)

	def __str__(self):
		return self.long_desc + ' (' + self.added_user + ')'

todo/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group, User
from django.http import HttpResponse, Http404
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from dal import autocomplete
from django.db.models import Q

from .forms import TodoForm, TodoNotesForm
from .models import Todo, Resource, Context, TodoStatus, ResourceGroup, TodoNotes
import util.uctutil as uu

#home view for posts. Posts are displayed in a list
class TodoIndexView(ListView):
  model = Todo
  template_name='todo/todo_index.html'
  context_object_name = 'todo_list'
  paginate_by = 15


  def get_queryset(self):
    # param_page = self.request.GET.get ('page')
    # if (param_page):
    #   print ("1---------->Page Param found in request")
      # qs = super().get_queryset()
      # print ("2---------->QS Count at Pagination", len(qs))
      # return qs;
    filters = Q()
    grp = ResourceGroup.objects.values ('group').filter (
          user__username =self.request.user, can_see_group_list=True)

    filter_param = self.request.GET.get ('filter', self.request.session.get ('filter_val', 'mylist'))
    if filter_param == 'mylist' or filter_param == self.request.user.username:
      filter_param = 'mylist'
    elif grp.count() == 0 and (filter_param == 'grplist' or filter_param != self.request.user.username):
      if self.request.session['filter_val']:
        self.request.session['filter_val'] = 'mylist'
      raise Http404 ("Not found")

    self.request.session['filter_val'] = filter_param
    if (filter_param=='mylist'):
      filters = Q(assigned_to__user=self.request.user)
      filters.add (Q(Q (added_user__user=self.request.user) & Q(assigned_to__user__isnull=True)), Q.OR)
    elif (filter_param=='grplist'):
      filters = Q(group__id__in=grp)
    else: # Assume parameter is for Assign To
      filters = Q(group__id__in=grp)
      filters.add (Q(assigned_to__user__username=filter_param), Q.AND)

    ## Append base status filter for Status [All/Completed/Non-Completed]
    status_param = self.request.GET.get ('status', self.request.session.get ('status_val', 'open'))
    if status_param == 'all':
      # No filter based on status
      self.request.session['status_val'] = status_param
    elif status_param == 'completed':
      self.request.session['status_val'] = status_param
      filters.add (Q(status_id__code='COM'), Q.AND)
    else:
      self.request.session['status_val'] = status_param
      filters.add (~Q(status_id__code='COM'), Q.AND)

#    print ('10---------->Filters', filters)
    
    ob = ['-added_date', 'context_id']
    qs = Todo.objects.filter (filters).order_by(*ob)
    return qs

  def get_context_data(self, **kwargs):
    context = super(TodoIndexView, self).get_context_data(**kwargs)
    context['filter'] = self.request.GET.get('filter', 'mylist')
    users = Resource.objects.filter(
      user__in = ResourceGroup.objects.values ('user').filter(
        group__in=ResourceGroup.objects.values ('group').filter (
          user__username =self.request.user, can_see_group_list=True))).order_by ("res_name")
    context['res'] = users
    return context    

class ContextAutocomplete(autocomplete.Select2QuerySetView):
  def get_queryset(self):
  # Don't forget to filter out results depending on the visitor !
  #if not self.request.user.is_authenticated:
  #  return Resource.objects.none()

    qs = Context.objects.all().order_by('-context_id')
    if self.q:
      qs = qs.filter(Q(context_id__icontains=self.q) | Q(context_name__icontains=self.q)).order_by('-context_id')

    return qs

#Detail view (view post detail)
class TodoDetailView(DetailView):
  model=Todo
  template_name = 'todo/todo_detail.html'

@login_required
def todo_create(request):
  form = TodoForm(request.user, 'create', request.POST or None)
  if request.method == 'POST':
    form = TodoForm(request.user, 'create', request.POST)
    if form.is_valid():
      instance = form.save (commit=False)
      res = Resource.objects.filter(user=request.user).first()
      instance.added_user = res
      instance.modified_user = res
      instance.save()
      print ('Adding record--------------->', request.user, '->', instance.id)
      return redirect('todo_index')

  return render(request,'todo/todo_create.html',{'form': form})

@login_required (redirect_field_name='next')
def todo_close(request, pk, template_name='todo/todo_close.html'):
    todo = get_validated_todo (pk, request.user)    
    form = TodoForm(request.user, 'close', request.POST or None, instance=todo)
    form.fields['created_by'].initial = todo.added_user
    if form.is_valid():
        print ('Completing record--------------->', request.user, '->', pk)            
        instance = form.save (commit=False)
        instance.status = TodoStatus.objects.filter (code='COM').first()
        res = Resource.objects.filter(user=request.user).first()
        instance.modified_user = res
        instance.save()
        next = request.GET.get("next", None)
        if next is None:
          print ('Next is none.............')
          return redirect('todo_index')
        else:
          print ('Next is Not none.............', next)
          return redirect (next)

    return render(request, template_name, {'form':form})

@login_required (redirect_field_name='next')
def todo_edit(request, pk, template_name='todo/todo_edit.html'):
  form = None
  formNote = None
  notes = ''
  if request.method == 'POST':
    if request.POST.get('post') == 'Post':  # Block for post notes on task
      formNote = TodoNotesForm (data=request.POST)
      if formNote.is_valid():
        print ('Adding Notes--------------->', request.user, '->', pk)
        formNote.save ()

      todo = get_object_or_404(Todo, pk=pk)
      form = TodoForm(request.user, 'edit', None, instance=todo)
      form.fields['created_by'].initial = todo.added_user

      ob = ['-added_date',]
      notes = TodoNotes.objects.filter(todo=todo).order_by (*ob)
      messages.success(request, 'New note added!')
      return render(request, template_name, {'form':form, 'formNote': formNote, 'notes':notes})
    else:
      todo = get_validated_todo (pk, request.user)
      form = TodoForm(request.user, 'edit', request.POST or None, instance=todo)
      if form.is_valid():
        print ('Editing record--------------->', request.user, '->', pk)
        instance = form.save (commit=False)
        res = Resource.objects.filter(user=request.user).first()
        instance.modified_user = res
        instance.save()
    next = request.GET.get("next", None)
    if next is None:
      return redirect('todo_index')
    else:
      return redirect (next)
  elif request.method == 'GET':
    todo = get_object_or_404(Todo, pk=pk)
    form = TodoForm(request.user, 'edit', None, instance=todo)
    form.fields['created_by'].initial = todo.added_user
    ob = ['-added_date',]
    notes = TodoNotes.objects.filter(todo=todo).order_by (*ob)
    formNote = TodoNotesForm (initial={
      'todo': Todo.objects.get(id=pk),
      'added_user': Resource.objects.filter(user=request.user).first(),
    });
#  else:
#    return redirect('todo_index')

  return render(request, template_name, {'form':form, 'formNote': formNote, 'notes':notes})
  
@login_required (redirect_field_name='next')
def todo_copyas(request, pk, template_name='todo/todo_copyas.html'):
    todo = get_validated_todo (pk, request.user)
    todo.pk = None
    form = TodoForm(request.user, 'copyas', request.POST or None, instance=todo)
    form.fields['created_by'].initial = todo.added_user
    if form.is_valid():
        print ('CopyAs record--------------->', request.user, '->', pk)
        instance = form.save (commit=False)
        res = Resource.objects.filter(user=request.user).first()        
        instance.added_user = res
        instance.added_date = None
        instance.modified_user = res
        instance.save()
        next = request.GET.get("next", None)
        if next is None:
          print ('Next is none.............')
          return redirect('todo_index')
        else:
          print ('Next is Not none.............', next)
          return redirect (next)
    return render(request, template_name, {'form':form})

@login_required
def todo_delete(request, pk, template_name='todo/todo_delete.html'):
    todo = get_validated_todo (pk, request.user)
    form = TodoForm(request.user, 'delete', request.POST or None, instance=todo)    
    form.fields['created_by'].initial = todo.added_user
    if form.is_valid():
        print ('Deleting record--------------->', request.user, '->', pk)
        todo.delete()
        next = request.GET.get("next", None)
        if next is None:
          print ('Next is none.............')
          return redirect('todo_index')
        else:
          print ('Next is Not none.............', next)
          return redirect (next)
    return render(request, template_name, {'form':form})

@login_required
def todo_heatmap(request, template_name='todo/todo_heatmap.html'):
    start_param = request.GET.get ('start_date', None)
    offset      = request.GET.get ('offset', None)
    hm_list = uu.get_heatmap (start_param, offset)
#    print (hm_list)
#    return render(request, template_name, {'hm_list':hm_list.items()})
    return render(request, template_name, {'hm_list':hm_list})

def get_validated_todo (pk, user):
    filters = Q()
    grp = ResourceGroup.objects.values ('group').filter (
          user__username =user, can_edit_group_list=True)

    filters = Q(Q(pk=pk) & 
                Q(Q(assigned_to__user=user) | 
                  Q(Q(added_user__user=user) & Q(assigned_to__user__isnull=True)) |
                  Q(group__id__in=grp)))
#    print (filters)
    return get_object_or_404(Todo, filters)

todo/templates/todo/todo_close.html
{% extends "uauth/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{{ form.media }}
<br>
<div class="container" style="background-color: #e9ecef;">
  <h1 class="display-6">Close TODO</h1>
  <hr >
    {% crispy form %}
<script type="text/javascript">
	$("#id_start_date").datetimepicker({
      format:'d-M-Y',timepicker: false
	});
	$("#id_end_date").datetimepicker({
      format:'d-M-Y',timepicker: false
	});	
</script>    
</div>
{% endblock %}

todo/templates/todo/todo_copyas.html
{% extends "uauth/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{{ form.media }}
<br>
<div class="container" style="background-color: #e9ecef;">
  <h1 class="display-6">CopyAs TODO</h1>
  <hr >
    {% crispy form %}
<script type="text/javascript">
	$("#id_start_date").datetimepicker({
      format:'d-M-Y',timepicker: false
	});
	$("#id_end_date").datetimepicker({
      format:'d-M-Y',timepicker: false
	});	
</script>    
</div>
{% endblock %}

todo/templates/todo/todo_create.html
{% extends "uauth/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{{ form.media }}
<br>
<div class="container" style="background-color: #e9ecef;">
  <h1 class="display-6">New TODO</h1>
  <hr >
    {% crispy form %}
<script type="text/javascript">
	$("#id_start_date").datetimepicker({
      format:'d-M-Y',timepicker: false
	});
	$("#id_end_date").datetimepicker({
      format:'d-M-Y',timepicker: false
	});	
</script>    
</div>
{% endblock %}

todo/templates/todo/todo_delete.html
{% extends "uauth/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{{ form.media }}
<br>
<div class="container" style="background-color: #e9ecef;">
  <h1 class="display-6">Delete TODO</h1>
  <hr >
    {% crispy form %}
<script type="text/javascript">
  $("#id_start_date").datetimepicker({
      format:'d-M-Y',timepicker: false
  });
  $("#id_end_date").datetimepicker({
      format:'d-M-Y',timepicker: false
  }); 
</script>    
</div>
{% endblock %}

todo/templates/todo/todo_edit.html
{% extends "uauth/base.html" %}
{% load crispy_forms_tags %}
{% load todo_extras %}

{% block content %}
{{ form.media }}
<br>
<div class="container" style="background-color: #e9ecef;">
  <h1 class="display-6">Edit TODO</h1>
  <hr >
    {% crispy form %}
</div>
<script type="text/javascript">
	$("#id_start_date").datetimepicker({
      format:'d-M-Y',timepicker: false
	});
	$("#id_end_date").datetimepicker({
      format:'d-M-Y',timepicker: false
	});	
</script><br> 

<div class="container" style="background-color: #e9ecef;">
  {% for note in notes.all %}
  {% if forloop.first %}
    <P>{{ notes.count|expluralize:'Note' }}</P>
  {% endif %}
    <b>{{ note.added_user }}</b> on {{ note.added_date }}<br>
    <P>{{ note.notes }}</P>
  {% empty %}
    <P>No notes for this task</P>
  {% endfor %}
  {% crispy formNote %} <br>
  <div id='form-errors'>{{ formNote.errors }}</div>  
</div>
{% endblock %}

todo/templates/todo/todo_heatmap.html
{% extends "uauth/base.html" %}
{% load todo_extras %}

{% block content %}
<script type="text/javascript">
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
<br>
<div class="container">
<div class="row row-g">
  <div class="col">
    <table id="actionPanel" width="100%" cellpadding="1" cellspacing="0" border="0" class="ta">
    <tr valign="middle" class="st">
        <td align="right" class="NormalText">
          <a class="btn btn-outline-primary" href="{% url 'todo_create' %}" data-toggle="tooltip" title="Create new item"><span class="oi oi-plus"></span></a>
          <a class="btn btn-outline-primary" data-toggle="tooltip" title="Edit selected item"
             href="javascript:void(0)"
             onclick="getActionButtonClicked(document.form1, '{% url 'todo_edit' '999' %}', '?next={{request.path}}?{{request.GET.urlencode}}')"/>
             <span class="oi oi-pencil"></span>
          </a>
          <a class="btn btn-outline-primary" data-toggle="tooltip" title="Copy selected item as..."
             href="javascript:void(0)"
             onclick="getActionButtonClicked(document.form1, '{% url 'todo_copyas' '999' %}', '?next={{request.path}}?{{request.GET.urlencode}}')"/>
             <span class="oi oi-fork"></span>
          </a>
          <a class="btn btn-outline-success" data-toggle="tooltip" title="Mark selected item completed"
             href="javascript:void(0)"
             onclick="getActionButtonClicked(document.form1, '{% url 'todo_close' '999' %}', '?next={{request.path}}?{{request.GET.urlencode}}')"/>
             <span class="oi oi-task"></span>
          </a>&nbsp;&nbsp;
          <a class="btn btn-outline-danger" data-toggle="tooltip" title="Delete selected item"
             href="javascript:void(0)"
             onclick="getActionButtonClicked(document.form1, '{% url 'todo_delete' '999' %}', '?next={{request.path}}?{{request.GET.urlencode}}')"/>
             <span class="oi oi-trash"></span>
          </a>&nbsp;&nbsp;&nbsp;&nbsp;
          <a class="btn btn-outline-primary" href="{% url 'todo_index' %}" data-toggle="tooltip" title="View Tabular">
            <span class="oi oi-spreadsheet"></span></a>
        </td>        
    </tr>
    </table>
  </div>
</div>
<svg width="585" height="{% widthratio 25 1 hm_list.1|length %}" class="tt" style="border:1px solid red">
  <g transform="translate(110, 70)">
    {% for values in hm_list.1 %}
      {% if forloop.first %}
        <g transform="translate(0, -5)">
          {% for v in hm_list.0 %}
            {% if forloop.first %}
              <text text-anchor="start" font-weight="bold" class="wday" x="-99" y="8">Name</text>
            {% else %}
              <text text-anchor="start" font-weight="bold" transform="rotate(90)" class="wday" 
                x="-60" y="{% widthratio -15 1 forloop.counter|add:'-1' %}">{{v}}</text>
            {% endif %}
          {% endfor %}
        </g>
      {% endif %}

      <g transform="translate(0, {% widthratio 15 1 forloop.counter %})">
        {% for v in values %}
          {% if forloop.first %}
            <text text-anchor="start" class="wday" dx="-99" dy="8">{{v|slugify}}</text>
          {% else %}
            {% if v|slugify == "-1" %}
              <rect class="day" width="10" height="10" x="{% widthratio 15 1 forloop.counter|add:'-1' %}" y="0"
                fill="var(--color-heatmap-day-weekend)" data-name="{{ values.0 }}" data-value="{{ v }}" 
                data-date="{{hm_list.0|get_name_by_index:forloop.counter}}"/>
                <title class="tooltiptext">{{values.0}} | {{hm_list.0|get_name_by_index:forloop.counter}} | Weekend</title></rect>
            {% elif v|slugify == "-2" %}
              <rect class="day" width="10" height="10" x="{% widthratio 15 1 forloop.counter|add:'-1' %}" y="0"
                fill="var(--color-heatmap-day-leave)" data-name="{{ values.0 }}" data-value="{{ v }}"
                data-date="{{hm_list.0|get_name_by_index:forloop.counter}}">
                <title class="tooltiptext">{{values.0}} | {{hm_list.0|get_name_by_index:forloop.counter}} | Leave</title></rect>
            {% elif v|slugify == "-3" %}
              <rect class="day" width="10" height="10" x="{% widthratio 15 1 forloop.counter|add:'-1' %}" y="0"
                fill="var(--color-heatmap-day-holiday)" data-name="{{ values.0 }}" data-value="{{ v }}"
                data-date="{{hm_list.0|get_name_by_index:forloop.counter}}">
                <title class="tooltiptext">{{values.0}} | {{hm_list.0|get_name_by_index:forloop.counter}} | Holiday</title></rect>
            {% elif v|slugify == "0" %}
              <rect class="day" width="10" height="10" x="{% widthratio 15 1 forloop.counter|add:'-1' %}" y="0"
                fill="var(--color-heatmap-day-L0)" data-name="{{ values.0 }}" data-value="{{ v }}"
                data-date="{{hm_list.0|get_name_by_index:forloop.counter}}">
                <title class="tooltiptext">{{values.0}} | {{hm_list.0|get_name_by_index:forloop.counter}} | No assignment</title></rect>
            {% elif v|slugify == "1" %}
              <rect class="day" width="10" height="10" x="{% widthratio 15 1 forloop.counter|add:'-1' %}" y="0"
                fill="var(--color-heatmap-day-L1)" data-name="{{ values.0 }}" data-value="{{ v }}"
                data-date="{{hm_list.0|get_name_by_index:forloop.counter}}">
                <title class="tooltiptext">{{values.0}} | {{hm_list.0|get_name_by_index:forloop.counter}} | Moderate engagement</title></rect>
            {% elif v|slugify == "2" %}
              <rect class="day" width="10" height="10" x="{% widthratio 15 1 forloop.counter|add:'-1' %}" y="0"
                fill="var(--color-heatmap-day-L2)" data-name="{{ values.0 }}" data-value="{{ v }}"
                data-date="{{hm_list.0|get_name_by_index:forloop.counter}}">
                <title class="tooltiptext">{{values.0}} | {{hm_list.0|get_name_by_index:forloop.counter}} | Multiple engagement</title></rect>
            {% else %}
              <rect class="day" width="10" height="10" x="{% widthratio 15 1 forloop.counter|add:'-1' %}" y="0"
                fill="var(--color-heatmap-day-L4)" data-name="{{ values.0 }}" data-value="{{ v }}"
                data-date="{{hm_list.0|get_name_by_index:forloop.counter}}">
                <title class="tooltiptext">{{values.0}} | {{hm_list.0|get_name_by_index:forloop.counter}} | High engagement</title></rect>
            {% endif %}
          {% endif %}
        {% endfor %}
      </g>
    {% endfor %}
  </g>
</svg>
<br>
<div class="row row-g">
  <div class="col">
    <table id="actionPanel" width="585" cellpadding="1" cellspacing="0" border="0" class="ta">
    <tr valign="middle" class="st">
      <td align="left" class="NormalText">
        <a class="btn btn-outline-primary" href="javascript:void(0)" data-toggle="tooltip" title="Previous 30 days"
           onclick="hmAction('prev', {% url 'todo_heatmap' %})">
          <span class="oi oi-chevron-left"></span>
        </a>
      </td>

      <td align="middle" class="NormalText">
        <div class="btn-group" role="group">
          <a class="btn btn-outline-primary" data-toggle="tooltip" title="Current date onwards"
            onclick="hmAction('today', {% url 'todo_heatmap' %})">
            <span class="oi oi-home"></span>            
          </a>&nbsp;          
          <input type="text" name="from_date" autocomplete="off" placeholder="Select a from date" title="From Date"
              class="datepicker dateinput form-control" id="id_from_date" value="{{hm_list.2}}"/>&nbsp;
          <a class="btn btn-outline-primary" data-toggle="tooltip" title="Update data"
            onclick="hmAction('option', {% url 'todo_heatmap' %})">Go</a>
          </a>              
        </div>
        </div>
      </td>
      <td align="right" class="NormalText">
        <a class="btn btn-outline-primary" href="javascript:void(0)" data-toggle="tooltip" title="Next 30 days"
           onclick="hmAction('next', {% url 'todo_heatmap' %})">
          <span class="oi oi-chevron-right"></span>
        </a>
      </td>
    </tr>
    </table>
  </div>
</div>
<script type="text/javascript">
  $("#id_from_date").datetimepicker({
      format:'d-M-Y',timepicker: false
  });

  sliders = document.querySelectorAll("rect");
  sliders.forEach(item=> {
    item.addEventListener('mouseover', (e) => {
      var o=e.target;
      o.style.stroke = "#ff0000";
      o.style.strokeWidth = "1";
//      console.log(`${item.getAttribute("data-count")} is this value`);
    });
    
    item.addEventListener('mouseout', (e) => {
      var o=e.target;
      o.style.stroke = "#000000";
      o.style.strokeWidth = "0";
    });   
    item.addEventListener('click', (e) => {
        var svgobj=e.target;
//        svgobj.setAttribute ('style', "stroke = #ff0000;stroke-width: 1");    
    svgobj.style.stroke = "#ff0000";
    svgobj.style.strokeWidth = "1";
    alert(svgobj.getAttribute("data-name") + svgobj.getAttribute("data-date") + svgobj.getAttribute("data-value"))
//      item.nextElementSibling.textContent = e.target.value;
    });   

  })
</script>
<div class="tt">Text<span class="tooltiptext">Tooltip text</span></div>
</div>

{% endblock %}